### ISSUE TITLE
Avoid duplicated efforts

### ISSUE THREAD

**Issue by AmitMY** [sign-language-translator/sign-language-translator#22]
Hi!
The goals of this repo seems to be very nice, but I think a lot of the work is already covered by:
https://github.com/sign-language-processing/

With [datasets](https://github.com/sign-language-processing/datasets) and a [translation pipeline](https://github.com/sign-language-processing/transcription)

As for the sign-stitching pipeline, can use https://github.com/ZurichNLP/spoken-to-signed-translation

You seem to be a very capable engineer, and I believe that joining efforts would be great.

**Comment by mdsrqbl** [comment]
Hey,

Thanks for providing these resources. I have visited some of the repos there in the past but, at the time, I couldn't see where to start working or how to quickly integrate those components into my project.

I have a bunch of ideas and some model architectures that I really want to implement so I am building all the components I need into a monolithic library so that the rest of the academia can also use them. I am very optimistic about the things coming ahead.

Also thank you for your kind words. I would be happy to contribute in building great solutions to the sign language translation problem.
